app/Http/routes.php
<?php

Route::auth();

Route::get('/', 'SiteController@index');
Route::get('about', ['as' => 'about', 'uses' => 'SiteController@about']);

Route::resource('area', 'AreaController');

Route::get('tours', ['as' => 'tour.index', 'uses' => 'TourController@index']);

Route::group(['prefix' => 'booking'], function () {
    Route::post('/', 'BookController@create');

    //выбор тура
    Route::get('/{user}/tours', ['as' => 'book.tours', 'uses' => 'BookController@tours']);

    //ввод контактных данных
    Route::get('/{user}/tours/{tour}/{trip}/book', ['as' => 'book.information', 'uses' => 'BookController@information']);

    //оплата
    Route::get('/{booking}/pay', ['as' => 'book.pay', 'uses' => 'BookController@pay']);

    //подтверждение
    Route::get('/{booking}/confirmation', ['as' => 'book.confirmation', 'uses' => 'BookController@confirmation']);

    Route::get('/{booking}/confirm', ['as' => 'book.confirm', 'uses' => 'BookController@confirm']);
    Route::get('/{booking}/cancel', ['as' => 'book.cancel', 'uses' => 'BookController@cancel']);
});





Route::group(['prefix' => 'profile'], function () {
    Route::get('/', ['as' => 'profile.index', 'uses' => 'Profile\ProfileController@index']);
    Route::get('toggleIsSeller', ['as' => 'profile.toggleIsSeller', 'uses' => 'Profile\ProfileController@toggleIsSeller']);
    Route::get('toggleSmsEnabled', ['as' => 'profile.toggleSmsEnabled', 'uses' => 'Profile\ProfileController@toggleSmsEnabled']);

    Route::group(['prefix' => 'phone'], function () {
        Route::get('/', ['as' => 'profile.phone.index', 'uses' => 'Profile\PhoneController@index']);
        Route::get('/confirm', ['as' => 'profile.phone.confirm', 'uses' => 'Profile\PhoneController@confirm']);
        Route::post('/confirm', ['as' => 'profile.phone.postConfirm', 'uses' => 'Profile\PhoneController@postConfirm']);
        Route::get('/newCode', ['as' => 'profile.phone.newCode', 'uses' => 'Profile\PhoneController@newCode']);
    });


    Route::group(['prefix' => 'sales'], function () {
        Route::get('/', ['as' => 'profile.sales', 'uses' => 'Profile\SaleController@index']);
        Route::get('/{booking}', ['as' => 'profile.sales.show', 'uses' => 'Profile\SaleController@show']);
        Route::get('/{booking}/confirm', ['as' => 'profile.sales.confirm', 'uses' => 'Profile\SaleController@confirm']);
        Route::get('/{booking}/cancel', ['as' => 'profile.sales.cancel', 'uses' => 'Profile\SaleController@cancel']);
    });


    Route::group(['prefix' => 'bookings'], function () {
        Route::get('/', ['as' => 'profile.bookings', 'uses' => 'Profile\BookingController@index']);
        Route::get('{booking}', ['as' => 'profile.bookings.show', 'uses' => 'Profile\BookingController@show']);
    });

    Route::group(['prefix' => 'tours'], function () {
        Route::get('/', ['as' => 'profile.tours', 'uses' => 'Profile\TourController@index']);


        Route::get('create', ['as' => 'profile.tours.create', 'uses' => 'Profile\TourController@create']);
        Route::post('create', ['as' => 'profile.tours.postCreate', 'uses' => 'Profile\TourController@postCreate']);

        Route::get('{tour}/edit', ['as' => 'profile.tours.edit', 'uses' => 'Profile\TourController@edit']);
        Route::patch('{tour}/edit', ['as' => 'profile.tours.update', 'uses' => 'Profile\TourController@update']);

        Route::get('{tour}/toggleIsHidden', ['as' => 'profile.tours.toggleIsHidden', 'uses' => 'Profile\TourController@toggleIsHidden']);


        //TRIPS:
        Route::get('{tour}/trip/create', ['as' => 'profile.tours.trip.create', 'uses' => 'Profile\TripController@create']);
        Route::post('{tour}/trip/create', ['as' => 'profile.tours.trip.postCreate', 'uses' => 'Profile\TripController@postCreate']);

        //редактирование trip
        Route::get('{tour}/trip/{trip}/edit', ['as' => 'profile.tours.trip.edit', 'uses' => 'Profile\TripController@edit']);
        Route::patch('{tour}/trip/{trip}/edit', ['as' => 'profile.tours.trip.update', 'uses' => 'Profile\TripController@update']);

        //создание tour_image
        Route::post('{tour}/image/create', ['as' => 'profile.tours.image.create', 'uses' => 'Profile\ImageController@uploadTourImage']);
        //удаление tour_image
        Route::get('image/{tour_image}/delete', ['as' => 'profile.tours.image.delete', 'uses' => 'Profile\ImageController@deleteTourImage']);
        //TRIPS end


        //TOUR days:
        Route::get('{tour}/day/create', ['as' => 'profile.tours.day.create', 'uses' => 'Profile\TourDayController@create']);
        Route::post('{tour}/day/create', ['as' => 'profile.tours.day.postCreate', 'uses' => 'Profile\TourDayController@postCreate']);

        //редактирование day
        Route::get('{tour}/day/{day}/edit', ['as' => 'profile.tours.day.edit', 'uses' => 'Profile\TourDayController@edit']);
        Route::patch('{tour}/day/{day}/edit', ['as' => 'profile.tours.day.update', 'uses' => 'Profile\TourDayController@update']);

        Route::get('{tour}/day/{day}/delete', ['as' => 'profile.tours.day.delete', 'uses' => 'Profile\TourDayController@deleteDay']);
    });
});


Route::get('t/{area}/{tour}/{trip}', ['as' => 'tour.showTourTrip', 'uses' => 'TourController@showTourTrip']);
Route::get('t/{area}/{tour}', ['as' => 'tour.showTour', 'uses' => 'TourController@showTour']);
Route::get('t/{area}/{tour}/{trip}/book', ['as' => 'book.trip', 'uses' => 'TourController@bookTrip']);

app/Models/Tour.php
<?php

namespace App\Models;

use App\Scopes\TourScope;
use Illuminate\Database\Eloquent\Model;

/**
 * @property User user
 * @property string name
 * @property integer id
 * @property string excerpt
 * @property string description
 * @property integer category
 * @property string price_includes
 * @property string price_excludes
 * @property integer complexity
 * @property string url_about
 * @property string capacity
 * @property boolean is_hidden
 *
 * @property Area area
 *
 */
class Tour extends Model {

    protected $table = 'tour';

    protected $fillable = [
        'user_id',
        'area_id',
        'name',
        'excerpt',
        'description',
        'category',
        'price_includes',
        'price_excludes',
        'complexity',
        'url_about',
        'capacity',
        'price',
        'is_hidden',
    ];

    public function comments() {
        return $this->hasMany('App\Models\Trip');
    }

    public function area() {
        return $this->belongsTo('App\Models\Area');
    }

    public function user() {
        return $this->belongsTo('App\Models\User');
    }

    public function trips() {
        return $this->hasMany('App\Models\Trip');
    }

    public function images() {
        return $this->hasMany('App\Models\TourImage');
    }

    public function days() {
        return $this->hasMany('App\Models\TourDay');
    }

    public function bookings() {
        return $this->hasManyThrough('App\Models\Booking', 'App\Models\Trip');
    }

    public function scopeActive($query) {
        return $query->where('is_hidden', false);
    }
}

app/Http/Controllers/Profile/TourController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\TourRequest;
use App\Http\Requests\TripRequest;
use App\Models\Booking;
use App\Models\Tour;
use App\Models\TourImage;
use App\Models\Trip;
use App\Models\User;
use App\Services\ImageService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;


class TourController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $user = Auth::user();
        return view('profile.tours.index', compact('user'));
    }

    public function create() {
        $user = Auth::user();
        return view('profile.tours.create', compact('user'));
    }

    public function postCreate(TourRequest $tourRequest) {
        /** @var User $user */
        $user = Auth::user();
        $tour = $user->tours()->create($tourRequest->all());
        return redirect()->route('profile.tours.edit', $tour->id);
    }

    public function edit(Tour $tour) {
        $user = Auth::user();
        return view('profile.tours.edit', compact('user', 'tour'));
    }

    public function update(Tour $tour, TourRequest $tourRequest) {
        $tour->update($tourRequest->all());
        return redirect()->route('profile.tours');
    }

    public function toggleIsHidden(Tour $tour) {
        $tour->update([
            'is_hidden' => !$tour->is_hidden
        ]);
        return redirect()->back();
    }
}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBookRequest;
use App\Models\Area;
use App\Models\Booking;
use App\Models\Tour;
use App\Models\Trip;
use App\Models\User;
use App\Services\BookingService;
use Illuminate\Http\Request;

use App\Http\Requests;


class TourController extends Controller {

    public function bookTrip(Area $area, Tour $tour, Trip $trip) {
        $bookingFormSrc = route('book.information', [$tour->user->id, $tour->id, $trip->id]);
        $backSrc = route('tour.showTourTrip', [$area->slug, $tour, $trip]);
        return view('tour.book', compact('tour', 'trip', 'bookingFormSrc', 'backSrc'));
    }

    public function index(Request $request) {
        $area = $request->input('area');
        $category = $request->input('category');

        $tours = Tour::active()->limit(50);

        if (!empty($area)) {
            $tours = $tours->where('area_id', $area);
        }
        if (!empty($category)) {
            $tours = $tours->where('category', $category);
        }
        $tours = $tours->get();

        return view('tour.index', compact('tours'));
    }

    public function create() {}

    public function store(Request $request) {}

    public function showTour(Area $area, Tour $tour) {
        $similar = Tour::active()->latest()->limit(3)->get();
        return view('tour.show', compact('tour', 'similar'));
    }

    public function showTourTrip(Area $area, Tour $tour, Trip $trip) {
        $similar = Tour::active()->latest()->limit(3)->get();
        return view('tour.show', compact('tour', 'trip', 'similar'));
    }

    public function edit($id) {}

    public function update(Request $request, $id) {}

    public function destroy($id) {}
}

resources/views/tour/book.blade.php
@extends('layouts.empty')

@section('content')

    <div class="container" style="margin-top:22px;">
        <div class="row">
            <div class="col-md-12">
                <a href="{{$backSrc}}">&larr; назад</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <iframe src="{{$bookingFormSrc}}" width="1000" height="1000" frameborder="0" scrolling="no"></iframe>
            </div>
        </div>
    </div> <!-- /container -->
@endsection

resources/views/tour/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .search-form-container {
            position: relative;
            padding-top: 20px;
            padding-bottom: 20px;
            background: rgba(0, 0, 0, 0.3);

        }
        .search-form-image {
            background-size: cover;
            background-image: url(/images/search1.jpg);
        }
    </style>
    <div class="search-form-image">
        @include('partials.search-panel')
    </div>
    <div class="container">
        <div class="row" style="margin-top:16px;">
            <div class="col-md-12">
                @if(isset($tours))
                    @foreach($tours as $tour)
                        @include('tour.list-item', [
                             'tour' => $tour,
                         ])
                        <hr/>
                    @endforeach
                @else
                    <div class="row">
                        <div class="col-md-12">
                            Туры не найдены
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div> <!-- /container -->
@endsection

resources/views/tour/list-item.blade.php
<div class="well">
    <div class="row tour-item-container">
        <div class="col-md-3">
            @if ($tour->images()->exists())

                @if ($tour->trips()->exists())
                    <a href="{{route('tour.showTourTrip', [$tour->area->slug, $tour->id, $tour->trips()->first()->id])}}" title="{{$tour->name}}">
                        <img src="{{$tour->images->first()->small_src}}" class="img-responsive"/>
                    </a>
                @else
                    <a href="{{route('tour.showTour', [$tour->area->slug, $tour->id])}}" title="{{$tour->name}}">
                        <img src="{{$tour->images->first()->small_src}}" class="img-responsive"/>
                    </a>
                @endif
            @endif
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-9">
                    <p class="tour-title">
                        <a class="tour-region" href="{{route('area.show', $tour->area->slug)}}" title="{{$tour->area->name}}">{{$tour->area->name}}</a>

                        <br/>
                        @if ($tour->trips()->exists())
                            <a href="{{route('tour.showTourTrip', [$tour->area->slug, $tour->id, $tour->trips()->first()->id])}}" title="{{$tour->name}}" class="tour-title-name">{{$tour->name}}</a>
                        @else
                            <a href="{{route('tour.showTour', [$tour->area->slug, $tour->id])}}" title="{{$tour->name}}" class="tour-title-name">{{$tour->name}}</a>
                        @endif

                        <br/>

                        @if ($tour->trips()->exists())
                            <i class="mdi mdi-calendar-clock mdi-24px mdi-dark mdi-inactive"></i>
                            {{$tour->trips()->first()->start_at->formatLocalized('%B, %d')}},
                            {{max($tour->trips()->first()->start_at->diffInDays($tour->trips()->first()->finish_at), 1)}} дн.
                        @endif
                    </p>
                    <p class="tour-description">
                        {{$tour->excerpt}}
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        <span class="tour-currency pull-right">руб</span>
                        <span class="tour-price pull-right">
                            @if ($tour->trips()->exists())
                                {{number_format($tour->trips()->first()->price, 0)}}
                            @else
                                {{number_format($tour->price, 0)}}
                            @endif
                        </span>

                        @if ($tour->trips()->exists())
                            <a href="{{route('tour.showTourTrip', [$tour->area->slug, $tour->id, $tour->trips()->first()->id])}}"
                               class="btn btn-success tour-book">
                                Подробнее
                            </a>
                        @else
                            <a href="{{route('tour.showTour', [$tour->area->slug, $tour->id])}}" class="btn btn-success tour-book">
                                Подробнее
                            </a>
                        @endif
                    </p>
                </div>
            </div>
        </div>
    </div>

</div>

resources/views/tour/show_old.blade.php
@extends('layouts.app')

@push('head')
    <link href="{{ elixir('compiled/trip-show.css') }}" rel="stylesheet" type="text/css" />
@endpush

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>
                    <small><a href="{{route('area.show', $tour->area->slug)}}">{{$tour->area->name}}</a> / </small>
                    {{$tour->name}}
                </h2>
                @if (isset($trip))
                    <p>
                        <span class="tour-info-dates">
                            {{$trip->start_at->formatLocalized('%d %B, %a')}} - {{$trip->finish_at->formatLocalized('%d %B, %a')}}
                        </span>
                    </p>
                @endif
                <p>
                    {{$tour->excerpt}}
                </p>
            </div>
        </div>

        @if ($tour->images()->exists())
            <div class="row">
                <div class="col-md-6">
                    @include('tour.partials.tour-carousel')
                </div>
                <div class="col-md-6">
                    @include('tour.partials.tour-info')
                </div>
            </div>
            <hr/>

            <div class="row">
                <div class="col-md-12">
                    <p>{!! $tour->description !!}</p>
                </div>
            </div>
        @else
            <div class="row">
                <div class="col-md-6">
                    @include('tour.partials.tour-info')
                </div>
                <div class="col-md-6">
                    <p>{!! $tour->description !!}</p>
                </div>
            </div>
        @endif

        @if ($tour->days()->exists())
        <hr/>
        @endif
        @foreach($tour->days as $dayKey => $day)
            <div class="row">
                <div class="col-md-2">
                    <h4>{{++$dayKey}} день</h4>
                </div>
                <div class="col-md-10">
                    <div class="well">
                        {!! $day->description !!}
                    </div>
                </div>
            </div>
        @endforeach


        @if (isset($trip) && $trip->responses()->exists())
        <hr id="testimonials"/>
        <div class="row">
            <div class="col-md-12 text-center">
                <h4>Отзывы</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="list-group">
                    @foreach($trip->responses as $response)
                        <li class="list-group-item">
                            @include('tour.response.list-item', ['response' => $response])
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
        @endif

        @if ($tour->trips()->count() > 1 || $tour->trips()->count() > 0 && !isset($trip))
        <hr id="trips"/>
        <div class="row">
            <div class="col-md-12">
                <h5>Другие даты этого тура</h5>
                <div class="list-group">
                    @foreach($tour->trips as $anotherTrip)
                        @if (!isset($trip) || $anotherTrip->id != $trip->id)
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-md-4">
                                {{$anotherTrip->start_at->formatLocalized('%d %B, %a')}} - {{$anotherTrip->finish_at->formatLocalized('%d %B, %a')}}
                            </div>
                            <div class="col-md-4">
                                {{$anotherTrip->price}} руб.
                            </div>
                            <div class="col-md-4">
                                <a class="btn btn-sm btn-warning"
                                   href="{{route('tour.showTourTrip', [$anotherTrip->tour->area->slug, $anotherTrip->tour->id, $anotherTrip->id])}}">
                                    Забронировать
                                </a>
                            </div>
                        </div>
                    </div>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
        @endif
    </div> <!-- /container -->

@endsection

@push('footer_scripts')
<style>
    .o-tour-dates-price-container {
        overflow: hidden;
        background: #ffffff;
        z-index: 999;
        width: 555px;
    }
    .o-tour-dates-price-container.affix {
        top: 20px;
        overflow: hidden;
        -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
        -moz-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
    }
    .o-tour-dates-price-container.affix-bottom {
        position: absolute;
        -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
        -moz-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
    }
</style>
@endpush